### ISSUE TITLE
Docker deployment error

### ISSUE THREAD

**Issue by crackman77** [gisaia/ARLAS-server#159]
Hi,

I'm currently testing ARLAS (both server & client) but fail to run docker image (both latest & 2.5.2 versions).

Currently Running Docker on Windows 10 64 bits : 
Docker Version 17.12.0-ce-win47 (15139)
Channel: stable
9c692cd

See image below showing the error
![image](https://user-images.githubusercontent.com/3404537/36205852-7a2d9910-1190-11e8-937b-8d8536f6ad1c.png)

A colleague of mine told me he had the same error.

Any insight on this?

Thanks 

Marc

**Comment by sfalquier** [comment]
Hi Marc,

Thanks for your interest in ARLAS stack.

ARLAS-server will fail fast if it cannot connect to the configured elasticsearch cluster. Can you ensure that you have an elasticsearch instance running at localhost:9200 for a cluster called "elasticsearch" that you can connect from your docker container?
Maybe you can take inspiration from our docker-compose file to set-up easily a running ARLAS-server instance. We will provide soon a docker-compose file for the whole stack.

That said, coud you give us `docker logs` of your ARLAS-server container at start-up so that we can understand what went wrong?

Sebastien

**Comment by crackman77** [comment]
Hi,

yes it seems to be all set up :

![image](https://user-images.githubusercontent.com/3404537/36245940-b27af842-122d-11e8-83d4-cc4c19662fba.png)

No more success with logs : 
![image](https://user-images.githubusercontent.com/3404537/36246099-678209d8-122e-11e8-9d5f-2786c6a7213f.png)
![image](https://user-images.githubusercontent.com/3404537/36246214-fbbbd4da-122e-11e8-8314-8f2f42872b8c.png)



I'll give it a try with docker-compose.

Thanks

Marc

**Comment by sfalquier** [comment]
I guess your arlas-server containers are not able to reach elasticsearch cluster on 127.0.0.1:9200 since elasticsearch is not running under docker.

By the way, we are currently working actively on ARLAS stack documentation before officially sharing it with the community. If you cannot manage to fix your issue with my little tips, wait a couple of days and I am sure our future "Getting started" page will help you a lot to test our solution.

**Comment by MohamedHamouGisaia** [comment]
Hi Marc @crackman77 ,

The ARLAS stack has considerably evolved since last time you raised the encountered error (3 years ago!)

I invite you to follow this [Quick start](http://docs.arlas.io/arlas-tech/current/arlas-quick-start/) that will allow you to start the ARLAS stack with one command thanks to docker-compose.

We also have 3 tutorials to use ARLAS with
- [birdtracking data](http://docs.arlas.io/arlas-tech/current/arlas-birdtracking-tutorial/)
- [boats navigation data (AIS)](http://docs.arlas.io/arlas-tech/current/arlas-ais-tutorial/)
- [air pollution data](http://docs.arlas.io/arlas-tech/current/arlas-openaq-tutorial/)

Many thanks,
Mohamed

**Comment by MohamedHamouGisaia** [comment]
@sfalquier should we close this issue ?
